services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      VITE_API_URL: 127.0.0.1:8080
